raw_dir: raw
metadata_tsv: metadata/sample-metadata.tsv
r1_suffix: _R1.fastq.gz
r2_suffix: _R2.fastq.gz
cutadapt_extra: --minimum-length 50 -q 20,20
dada2:
  trim_left_f: 0
  trim_left_r: 0
  trunc_len_f: 0
  trunc_len_r: 0
use_existing_qiime_env: true
qiime_env_name: qiime2-amplicon-2024.10
classifier_qza: refs/V3V4-silva-138.2/silva-138.2-V3V4-uniq-classifier.qza
reference:
  region_label: V3V4
  silva_version: '138.2'
  silva_target: SSURef_NR99
  primers:
    forward: CCTACGGGNGGCWGCAG
    reverse: GACTACHVGGGTATCTAATCC
  symbiont_list: refs/symbiont_taxa.txt
gg2:
  seqs_qza: refs/GG2-raw/2024.09.backbone.full-length.fna.qza
  tax_qza:  refs/GG2-raw/2024.09.backbone.tax.qza
  outdir:   refs/GG2-V3V4
  sepp_ref_qza: refs/GG2-raw/2022.10.backbone.sepp-reference.qza
  classifier_qza: refs/GG2-V3V4/V3V4-uniq-classifier.qza
summary:
  group_column: group   # native_status / region
concordance:
  top_n: 50
